=== MolnarMarkPatrik/GMPOCBWebXML/GMPOCB_0930/GMPOCB_mozi.dtd
<!ELEMENT mozi (film)*>

<!ELEMENT film (rendezo+,szinesz+,íro+)>
<!ATTLIST film id ID #REQUIRED>
<!ATTLIST film mufaj (horror | romantikus | thiller) "horror">

<!ELEMENT rendezo EMPTY>
<!ATTLIST rendezo id ID #REQUIRED>
<!ATTLIST rendezo nev CDATA #IMPLIED>

<!ELEMENT szinesz (gyerekszinesz | musicalszinesz | szinkronszinesz)*>
<!ATTLIST szinesz id ID #REQUIRED>
<!ATTLIST szinesz nev CDATA #IMPLIED>

<!ELEMENT gyerekszinesz EMPTY>
<!ELEMENT musicalszinesz EMPTY>
<!ELEMENT szinkronszinesz EMPTY>

<!ELEMENT íro EMPTY>
<!ATTLIST íro id ID #REQUIRED>

=== MolnarMarkPatrik/GMPOCBWebXML/GMPOCB_0930/GMPOCB_mozi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mozi SYSTEM "GMPOCB_mozi.dtd">
<mozi>
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex" />
        <szinesz id="u5g_4xm_2jb" nev="Madison_Ivy" />
        <szinesz id="a">
            <gyerekszinesz />
            <musicalszinesz />
            <szinkronszinesz />
        </szinesz>
        <íro id="trv_4xm_2jb" />
    </film>
</mozi>
